'use client';

import store from '@/components/store';
import './globals.css';

import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { persistStore } from 'redux-persist';

const persist = persistStore(store);

export const metadata = {
    title: 'Shopping Cart',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Provider store={store}>
                    <PersistGate persistor={persist}>{children}</PersistGate>
                </Provider>
            </body>
        </html>
    );
}
